from copy import deepcopy


def get_default_cfg():
    cfg = {
        "MODEL": {
            "BOX_MODE": "hbb",  # hbb | obb
            "TASK": "sgdet",  # predcls | sgcls | sgdet
            "NUM_CLASSES": 49,
            "NUM_PREDICATES": 59,
            "RPN_ONLY": False,
            "RETINANET_ON": False,
            "RELATION_ON": True,
            "ATTRIBUTE_ON": False,
            "MASK_ON": False,
            "KEYPOINT_ON": False,
            "FREEZE_BACKBONE": False,
            "FREEZE_NECK": False,
            "FREEZE_RPN_HEAD": False,
            "FREEZE_ROI_HEAD": False,
            "BACKBONE": {
                "NAME": "resnet_backbone",
                "OUT_CHANNELS": 256,
                "RESNET_NAME": "resnet50",
                "PRETRAINED": False,
            },
            "NECK": {
                "NAME": "fpn_neck",
                "IN_CHANNELS": [256, 512, 1024, 2048],
                "OUT_CHANNELS": 256,
            },
            "PROPOSAL_GENERATOR": {
                "NAME": "dummy_proposal_generator",
                "NUM_PROPOSALS": 64,
            },
            "ROI_EXTRACTOR": {
                "NAME": "simple_roi_extractor",
                "OUT_CHANNELS": 256,
                "POOL_SIZE": 7,
                "FEATMAP_NAMES": ["p2", "p3", "p4", "p5"],
                "FEATMAP_STRIDES": [4, 8, 16, 32],
                "FINEST_SCALE": 56,
            },
            "ROI_BOX_HEAD": {
                "FC_DIM": 1024,
                "NUM_CLASSES": 49,
                "BOX_LOSS_WEIGHT": 1.0,
                "CLS_LOSS_WEIGHT": 1.0,
            },
            "ROI_HEADS": {
                "FG_IOU_THRESHOLD": 0.5,
                "BG_IOU_THRESHOLD": 0.3,
                "BATCH_SIZE_PER_IMAGE": 256,
                "POSITIVE_FRACTION": 0.5,
                "DETECTIONS_PER_IMG": 80,
            },
            "ROI_RELATION_HEAD": {
                "USE_GT_BOX": False,
                "USE_GT_OBJECT_LABEL": False,
                "NUM_CLASSES": 59,
                "BATCH_SIZE_PER_IMAGE": 512,
                "MAX_TEST_PAIRS_PER_IMAGE": 10000,
                "TEST_PAIR_SAMPLER": "ALL",
                "TEST_SUBGRAPH_TOPK": 32,
                "TEST_SUBGRAPH_GLOBAL_TOPK": 0,
                "TEST_SUBGRAPH_COMPLETION_TOPK": 0,
                "POSITIVE_FRACTION": 0.25,
                "PREDICT_USE_VISION": True,
                "REQUIRE_BOX_OVERLAP": False,
                "PREDICTOR": "UNIMPLEMENTED",
                "CONTEXT_HIDDEN_DIM": 512,
                "CONTEXT_POOLING_DIM": 256,
                "EMBED_DIM": 200,
                "WORD_EMBEDDING_FEATURES": True,
                "EDGE_FEATURES_REPRESENTATION": "fusion",
                "USE_PAIR_SCALE_ENCODER": True,
                "UNION_MULTI_SCALE_POOLING": True,
                "RPCM_MLP_DIM": 1024,
                "RPCM_FEAT_UPDATE_STEP": 1,
                "RPCM_DROPOUT": 0.2,
                "RPCM_MARGIN": 0.2,
                "RPCM_USE_PROTOTYPE": True,
                "RPCM_PROTO_MOMENTUM": 0.9,
                "RPCM_PROTO_INIT": "semantic",
                "RPCM_OBJ_PROTO_INIT": "semantic",
                "RPCM_PAIR_LABEL_PRIOR": True,
                "RPCM_PAIR_PRIOR_DIM": 128,
                "PROTO_SEMANTIC_PUSH_ENABLED": True,
                "PROTO_ANTONYM_PAIRS": [],
                "PROTO_COMPETITOR_PAIRS": [],
                "PROTO_LAMBDA_PULL": 0.2,
                "PROTO_LAMBDA_SEP": 0.002,
                "PROTO_LAMBDA_ANT_SEP": 0.05,
                "PROTO_LAMBDA_COMP_SEP": 0.005,
                "PROTO_ANT_SEP_MARGIN": -0.10,
                "PROTO_COMP_SEP_MARGIN": 0.10,
                "PROTO_SEP_TYPE": "etf",
                "PROTO_TEXT_INIT_MODIFIER_AWARE": True,
                "SEMANTIC_GLOVE_PATH": "",
                "NUM_SUBGRAPH_QUERIES": 8,
                "SUBGRAPH_ATTENTION_HEADS": 4,
                "SUBGRAPH_DROPOUT": 0.1,
                "HIER_USE_PROTOTYPE": True,
                "HIER_PROTO_MOMENTUM": 0.9,
                "HIER_PAIRNESS_SCORE_WEIGHT": 1.0,
                "HIER_MARGIN": 0.2,
                "PREDICATE_LOSS_TYPE": "ce",  # ce | class_balanced | logit_adjusted
                "PREDICATE_CLASS_BALANCED_BETA": 0.999,
                "PREDICATE_BG_LOSS_WEIGHT": 1.0,
                "PREDICATE_LOGIT_ADJUST_TAU": 1.0,
                "PREDICATE_COUNTS": [],
                "NUM_SAMPLE_PER_GT_REL": 4,
                "TAIL_AWARE_POS_SAMPLING": False,
                "TAIL_AWARE_POS_ALPHA": 0.5,
                "TAIL_AWARE_POS_MIN_COUNT": 1.0,
                "TEST_FILTER_METHOD": "NONE",
                "SEMA_F_ENABLED": False,
                "SEMA_F_PATH": "pretrained/SF_list_support.json",
                "PPG_ENABLED": False,
                "PPG_PAIR_THRESHOLD": 10000,
                "PPG_TOPK": 10000,
                "TEST_FILTER_TOPK": 10000,
                "PPG_CHUNK_SIZE": 100000,
                "PPG_ENCODING_DIM": 25,
                "PPG_HIDDEN_DIM1": 50,
                "PPG_HIDDEN_DIM2": 50,
                "PPG_MODEL_PATH_OBB": "pretrained/STAR_OBB.pth",
                "PPG_MODEL_PATH_HBB": "pretrained/STAR_HBB.pth",
                "CAUSAL": {
                    "SPATIAL_FOR_VISION": True,
                },
            },
            "RELATION_HEAD": {
                "NAME": "latent_subgraph_relation_head",
                "NODE_DIM": 256,
                "EDGE_DIM": 256,
                "HIDDEN_DIM": 256,
                "NUM_PREDICATES": 59,
                "NUM_SUBGRAPHS": 8,
                "NUM_INTRA_LAYERS": 2,
                "NUM_INTER_LAYERS": 2,
                "NUM_ATTENTION_HEADS": 4,
                "MAX_REL_PAIRS": 256,
                "USE_GEOMETRY": True,
            },
        },
        "DATASETS": {
            "TRAIN": {
                "NAME": "generic_sgg_json",
                "ANN_FILE": "",
                "IMAGE_ROOT": "",
                "FILTER_EMPTY_RELATIONS": False,
                "TILE_ENABLED": False,
                "TILE_SIZE": [1024, 1024],
                "TILE_STRIDE": [768, 768],
                "TILE_CONTEXT": [0, 0],
                "TILE_MIN_OBJECTS": 1,
            },
            "VAL": {
                "NAME": "generic_sgg_json",
                "ANN_FILE": "",
                "IMAGE_ROOT": "",
                "FILTER_EMPTY_RELATIONS": False,
                "TILE_ENABLED": False,
                "TILE_SIZE": [1024, 1024],
                "TILE_STRIDE": [768, 768],
                "TILE_CONTEXT": [0, 0],
                "TILE_MIN_OBJECTS": 1,
            },
            "TEST": {
                "NAME": "generic_sgg_json",
                "ANN_FILE": "",
                "IMAGE_ROOT": "",
                "FILTER_EMPTY_RELATIONS": False,
                "TILE_ENABLED": False,
                "TILE_SIZE": [1024, 1024],
                "TILE_STRIDE": [768, 768],
                "TILE_CONTEXT": [0, 0],
                "TILE_MIN_OBJECTS": 1,
            },
        },
        "DATALOADER": {
            "BATCH_SIZE": 2,
            "TRAIN_BATCH_SIZE": 8,
            "VAL_BATCH_SIZE": 4,
            "TEST_BATCH_SIZE": 4,
            "NUM_WORKERS": 6,
        },
        "SOLVER": {
            "OPTIMIZER": "SGD",
            "BASE_LR": 1e-4,
            "WEIGHT_DECAY": 1e-4,
            "WEIGHT_DECAY_BIAS": 1e-4,
            "BIAS_LR_FACTOR": 1.0,
            "BETAS": (0.9, 0.999),
            "EPS": 1e-8,
            "MOMENTUM": 0.9,
            "WARMUP_ITERS": 0,
            "WARMUP_EPOCHS": 0,
            "WARMUP_FACTOR": 0.001,
            "WARMUP_METHOD": "linear",
            "MAX_EPOCHS": 12,
            "STEPS": [],
            "GAMMA": 0.1,
            "CHECKPOINT_PERIOD": 1,
            "VAL_PERIOD": 1,
            "VAL_START_PERIOD": 0,
            "PRINT_GRAD_FREQ": 0,
            "GRAD_NORM_CLIP": 5.0,
            "SCHEDULE": {
                "TYPE": "WarmupMultiStepLR",
                "UNIT": "iter",
                "MAX_ITERS": 0,
                "MIN_LR_RATIO": 0.0,
                "EXP_GAMMA": 0.999,
                "PATIENCE": 2,
                "THRESHOLD": 0.001,
                "COOLDOWN": 0,
                "FACTOR": 0.1,
                "MAX_DECAY_STEP": 3,
            },
            "OUTPUT_DIR": "outputs/default",
        },
        "RUNTIME": {
            "DISABLE_CUDNN": True,
            "CUDNN_BENCHMARK": False,
            "CUDNN_DETERMINISTIC": True,
        },
        "TEST": {
            "RECALL_AT": [20, 50, 100],
            "IOU_THRESHOLD": 0.5,
            "EVAL_DEBUG": {
                "ENABLED": False,
                "TOP_PREDICATES": 10,
                "TOP_IMAGES": 10,
            },
            "GRAPH_DEBUG": {
                "ENABLED": False,
            },
            "TILE_MERGE_IOU_THRESHOLD": 0.6,
            "PATCH_AUTO_ENABLED": True,
            "PATCH_AUTO_MIN_SIZE": 1024,
            "PATCH_MAX_PYRAMID_LAYERS": 8,
            "PATCH_BATCH_SIZE": 2,
            "PATCH_BATCH_SIZE_LARGE": 4,
            "PATCH_GAPS": [200],
            "PATCH_SIZE": [1024, 1024],
            "PATCH_SCORE_THRESHOLDS": [0.3, 0.2, 0.1, 0.001, 0.00001],
        },
        "TYPE": "CV",
        "mbs": 512,
        "feat_update_step": 4,
        "EXP_nums": 30,
    }
    return deepcopy(cfg)
